refactoring/katacodaPathHandling
devonfw-forge/tutorial-compiler pull request #93
Opened 2021-01-18 10:54 UTC by denise-khuu

2021-01-18 14:22 UTC, GuentherJulian requested changes

2021-01-18 14:22 UTC, GuentherJulian commented on runners/katacoda/templates/buildJava.md
Also add this to the template for 'npm install'

2021-01-18 14:22 UTC, GuentherJulian commented on runners/katacoda/index.ts
> +    private useDevonCommand: boolean = false;
We will use these variables in both runners. So we can move the variables to the runner base class.

2021-01-21 06:57 UTC, maybeec submitted a review, later dismissed

2021-01-25 10:16 UTC, GuentherJulian requested changes

2021-01-25 10:16 UTC, GuentherJulian commented on runners/katacoda/index.ts
> +
For the strings "workingDir" and "useDevonCommand" you can create contants and use them in setVariable() and getVariable(). Then it is easier to change the name later and it protects against spelling mistakes.

2021-01-25 12:00 UTC, GuentherJulian approved these changes

2021-01-25 12:21 UTC, merged